CREATE TABLE [staging].[fact_goalie_stats_per_60_20260206_082623] (

	[player_id] int NULL, 
	[home_team_id] int NULL, 
	[away_team_id] int NULL, 
	[game_id] int NULL, 
	[team_id] int NULL, 
	[total_assists] bigint NULL, 
	[total_goals] bigint NULL, 
	[total_shots] bigint NULL, 
	[total_saves] bigint NULL, 
	[total_powerPlaySaves] bigint NULL, 
	[total_shortHandedSaves] bigint NULL, 
	[total_evenSaves] bigint NULL, 
	[total_shortHandedShotsAgainst] bigint NULL, 
	[total_evenShotsAgainst] bigint NULL, 
	[total_powerPlayShotsAgainst] bigint NULL, 
	[assists_per_60] float NULL, 
	[goals_per_60] float NULL, 
	[shots_per_60] float NULL, 
	[saves_per_60] float NULL, 
	[powerPlaySaves_per_60] float NULL, 
	[shortHandedSaves_per_60] float NULL, 
	[evenSaves_per_60] float NULL, 
	[shortHandedShotsAgainst_per_60] float NULL, 
	[evenShotsAgainst_per_60] float NULL, 
	[powerPlayShotsAgainst_per_60] float NULL, 
	[total_toi_min] float NULL, 
	[season] varchar(max) NULL, 
	[type] varchar(max) NULL, 
	[date_time_GMT] datetime2(6) NULL, 
	[away_goals] int NULL, 
	[home_goals] int NULL, 
	[outcome] varchar(max) NULL, 
	[away_team_shortName] varchar(max) NULL, 
	[away_team_name] varchar(max) NULL, 
	[away_team_abbr] varchar(max) NULL, 
	[home_team_shortName] varchar(max) NULL, 
	[home_team_name] varchar(max) NULL, 
	[home_team_abbr] varchar(max) NULL, 
	[firstName] varchar(max) NULL, 
	[lastName] varchar(max) NULL, 
	[primaryPosition] varchar(max) NULL, 
	[venue] varchar(max) NOT NULL
);